import type { AriaAttributeData } from './types';

export const ariaAttributesData: AriaAttributeData[] = [
  { name: 'aria-activedescendant', type: 'id', global: true },
  { name: 'aria-atomic', type: 'boolean', global: true },
  {
    name: 'aria-autocomplete',
    type: 'token',
    global: true,
    values: ['inline', 'list', 'both', 'none'],
  },
  { name: 'aria-busy', type: 'boolean', global: true },
  {
    name: 'aria-checked',
    type: 'token',
    global: false,
    values: ['true', 'false', 'mixed'],
  },
  { name: 'aria-colcount', type: 'integer', global: false },
  { name: 'aria-colindex', type: 'integer', global: false },
  { name: 'aria-colspan', type: 'integer', global: false },
  { name: 'aria-controls', type: 'idlist', global: true },
  {
    name: 'aria-current',
    type: 'token',
    global: false,
    values: ['page', 'step', 'location', 'date', 'time', 'true', 'false'],
  },
  { name: 'aria-describedby', type: 'idlist', global: true },
  { name: 'aria-details', type: 'id', global: true },
  { name: 'aria-disabled', type: 'boolean', global: true },
  { name: 'aria-errormessage', type: 'id', global: true },
  { name: 'aria-expanded', type: 'boolean', global: false },
  { name: 'aria-flowto', type: 'idlist', global: true },
  {
    name: 'aria-haspopup',
    type: 'token',
    global: false,
    values: ['false', 'true', 'menu', 'listbox', 'tree', 'grid', 'dialog'],
  },
  { name: 'aria-hidden', type: 'boolean', global: true },
  {
    name: 'aria-invalid',
    type: 'token',
    global: true,
    values: ['grammar', 'false', 'spelling', 'true'],
  },
  { name: 'aria-keyshortcuts', type: 'string', global: true },
  { name: 'aria-label', type: 'string', global: true },
  { name: 'aria-labelledby', type: 'idlist', global: true },
  { name: 'aria-level', type: 'integer', global: false },
  {
    name: 'aria-live',
    type: 'token',
    global: true,
    values: ['off', 'polite', 'assertive'],
  },
  { name: 'aria-modal', type: 'boolean', global: false },
  { name: 'aria-multiline', type: 'boolean', global: false },
  { name: 'aria-multiselectable', type: 'boolean', global: false },
  {
    name: 'aria-orientation',
    type: 'token',
    global: false,
    values: ['horizontal', 'vertical'],
  },
  { name: 'aria-owns', type: 'idlist', global: true },
  { name: 'aria-placeholder', type: 'string', global: false },
  { name: 'aria-posinset', type: 'integer', global: false },
  {
    name: 'aria-pressed',
    type: 'token',
    global: false,
    values: ['true', 'false', 'mixed', 'undefined'],
  },
  { name: 'aria-readonly', type: 'boolean', global: false },
  {
    name: 'aria-relevant',
    type: 'token',
    global: true,
    values: ['additions', 'removals', 'text', 'all'],
  },
  { name: 'aria-required', type: 'boolean', global: false },
  { name: 'aria-roledescription', type: 'string', global: true },
  { name: 'aria-rowcount', type: 'integer', global: false },
  { name: 'aria-rowindex', type: 'integer', global: false },
  { name: 'aria-rowspan', type: 'integer', global: false },
  { name: 'aria-selected', type: 'boolean', global: false },
  { name: 'aria-setsize', type: 'integer', global: false },
  {
    name: 'aria-sort',
    type: 'token',
    global: false,
    values: ['ascending', 'descending', 'none', 'other'],
  },
  { name: 'aria-valuemax', type: 'integer', global: false },
  { name: 'aria-valuemin', type: 'integer', global: false },
  { name: 'aria-valuenow', type: 'integer', global: false },
  { name: 'aria-valuetext', type: 'string', global: false },
];
